### PR TITLE
Added findAllEventsInNamedCalendar for Android

### PR DESCRIPTION
**Pull request by mightymop**
Added findAllEventsInNamedCalendar for Android...

### CODE REVIEW

**Comment by vogloblinsky** [comment]
@EddyVerbruggen Any news about this PR ?
I need a way to filter events in iOS and Android, and this API seems fine for me.
Thanks

**Comment by EddyVerbruggen** [comment]
Would be a great help if you could test that PR!

**Comment by vogloblinsky** [comment]
@EddyVerbruggen Ok i will test that on iOS and Android next monday, and give you a feedback about this PR.

**Comment by ffMathy** [comment]
Anything new in this PR? I see it also has conflicts that need to be solved.

**Comment by ffMathy** [comment]
@mightymop why did you close this?

**Pull request closed without merging**
