### PR TITLE
Added failure result to findEvent

### PR DESCRIPTION
**Pull request by dchao19**
Added failure result to make sure that the plugin is not always
returning a success callback.

I haven't tested if the only returning a successful callback is also a problem on android but this is my solution for it on iOS.

### CODE REVIEW

**Comment by EddyVerbruggen** [comment]
I understand your PR, but i don't consider not finding anything an error, it can easilty be checked in JS if the length of the returned array is > 0 and take it from there.

An error in my opinion is when your input is incorrect, or some unexpected exception is raised.

Also, this PR could potentially break current usage where people rely on stuff not to be found and then add the event.

**Comment by syndbg** [comment]
As @EddyVerbruggen said, this would break current usage and is not worth the errback.

However it makes perfect sense to throw an errback if for some reason you can't access the device's calendar and return events.

**Comment by dchao19** [comment]
Ah...didn't see the problem of backwards compatibility in this change...Sorry!

Anyways, I also didn't see checking the contents of array in the success handling, which I guess would be the better option for both of us.

Apologizes for my poor abilities in forethought....

**Comment by EddyVerbruggen** [comment]
And I appreciate your intent to contribute! :+1:

**Pull request closed without merging**
