### PR TITLE
fixed timezone issue with createinteractively

### PR DESCRIPTION
**Pull request by Freundschaft**
check https://github.com/EddyVerbruggen/Calendar-PhoneGap-Plugin/issues/304

### CODE REVIEW

**Comment by EddyVerbruggen** [comment]
Looks good, thanks for your analysis and fix! 👍

**Comment by Freundschaft** [comment]
no worries, thanks for making this plugin :+1:

**Comment by Freundschaft** [comment]
@ramingar but a problem occurs if you use the allday option
you'll get allDay is true but sec, min, hour are not 0.
as highlighted in https://github.com/EddyVerbruggen/Calendar-PhoneGap-Plugin/issues/304
there might be a side effect causing the problems you are seeing, but I am pretty sure that the commit was the correct solution for this issue.
if you don't use allday, then you'll not encounter that issue,

**Comment by ramingar** [comment]
@Freundschaft , I'm not using allday setting. But, look:

timezone01

... and when I launch the System Calendar App:

timezone_2

It's two hours late with the same Timezone (GMT+0200), so I find it's an incorrect behaviour. What do you think?

**Comment by Freundschaft** [comment]
very very strange, its somehow connected to the **** up way javascript handles timezones (more here) http://stackoverflow.com/questions/15141762/how-to-initialize-javascript-date-to-a-particular-timezone
let me check it the next days, obviously both should work, allday flag and setting correct time

**Comment by ramingar** [comment]
Yep, I think that's the way... that solution will could be the perfect solution.

**Comment by Freundschaft** [comment]
I didnt compile it yet, so its possible that it doesnt work at all, but if you have the time you can check if this is working https://github.com/gfnork/Calendar-PhoneGap-Plugin/commit/ff5e4fae094004624511e3f4145f19d98e40cf4a

**Comment by elbidone** [comment]
# Android Calendar behavior
@Freundschaft because of the exception you've related on #304, the [Android implementation](https://github.com/EddyVerbruggen/Calendar-PhoneGap-Plugin/blob/master/src/android/nl/xservices/plugins/accessor/AbstractCalendarAccessor.java#L523
) check that event duration is 24h AND hours, min and sec are **setted to 0 on locale time**.

```
public static boolean isAllDayEvent(final Date startDate, final Date endDate) {
    return
        ((endDate.getTime() - startDate.getTime()) % (24*60*60*1000) == 0) &&
            startDate.getHours() == 0 &&
            startDate.getMinutes() == 0 &&
            startDate.getSeconds() == 0 &&
            endDate.getHours() == 0 &&
            endDate.getMinutes() == 0 &&
            endDate.getSeconds() == 0;
  }
```
[Date.getHours](https://developer.android.com/reference/java/util/Date.html#getHours())
> Returns the hour represented by this Date object. The returned value is a number (0 through 23) representing the hour within the day that contains or begins with the instant in time represented by this Date object, **as interpreted in the local time zone**.

What I can't understand it's **how the previous version (<2.5.1) of this plugin can set "all day" if locale hour is not equal to 0**. The implementation should not allow it. 
Date.getHours() is deprecated, should be replaced by [Calendar.get(Calendar.HOUR_OF_DAY)](https://developer.android.com/reference/java/util/Calendar.html#HOUR_OF_DAY). I don't know if it could be the reason...

**Can you provide us the version of plugin and android OS you used when you've observed the bug on #304.** You can please also provide the timezones of your device and the Calendar App.

The Calendar App has its own timezone settings, maybe the exception is raised for some versions when device and calendar tz are different. It could explain why plugin set "all day" with an hour not set to 0, by point of view of the Calendar.

If the timezone setted on your device not match the timezone of the datetimes passed to plugin the event will not be considered as "all day" on Android Calendar.

# iCalendar behavior
iCalendar doesn't care about hours, if you set "all day" hours seems to be ignored. 
If an event has 24h duration then it's considered an all day event. And you can check that the [implementation of the plugin for iOS](https://github.com/EddyVerbruggen/Calendar-PhoneGap-Plugin/blob/master/src/ios/Calendar.m#L62
) doesn't check hours.

```java
int duration = _endInterval - _startInterval;
    int moduloDay = duration % (60 * 60 * 24);
    if (moduloDay == 0) {
      myEvent.allDay = YES;
```

**Comment by Freundschaft** [comment]
all previous versions had the problem that allday was not working on google, it seems that just no one noticed that it didnt work

**Comment by elbidone** [comment]
I disagree @Freundschaft, I use this plugin for various Apps on Android, and It works for me, tested on Android 4.1.1 and Android 5.1 with version 2.5.0 of the plugin (and previous). Below an example of event dates I sent to calendar:
StartDate of Event: 2015-07-30T03:00:00.000Z
endDate of Event: 2015-07-31T03:00:00.000Z

As you can see dates are not at 00:00:00 on UTC, my timezone is BRT.

Please provide more details to help us to reproduce the issue.

**Comment by Freundschaft** [comment]
ah okay, I was referring to all versions >4.2.6 I dont know how 2.5.0 did it, where can I find the 2.5.0 version? all tags I see are > 4

**Comment by elbidone** [comment]
Sorry, 4.5.0 not 2.5.0. Then I've tested on Android 4.1.1 and Android 5.1 with version 4.5.0 of the plugin

**Comment by Freundschaft** [comment]
which method are you using to invoke the creation? createEventinteractively?

my problem occured with this code block

```
var startDate = moment($scope.arrival).clone().startOf('day'); //$scope.arrival is an arbitrary date & time
var endDate = moment($scope.departure).clone().startOf('day'); //$scope.departureis an arbitrary date & time

$cordovaCalendar.createEventInteractively({
            title: $scope.name,
            location: $scope.name,
            notes: '',
            startDate: startDate,
            endDate: endDate
          }).then(function (result) {
            // success
          }, function (err) {
            // error
          });
```

by the way I just tested https://github.com/EddyVerbruggen/Calendar-PhoneGap-Plugin/pull/320 and it seems to solve the problem

**Comment by elbidone** [comment]
I used createEventInteractivelyWithOptions and tested also createEventInteractively, both works fine with plugin version 4.5.0 (and previous) on Android 4.1 and 5.1.  
**Can you provide us the version of plugin and android OS you used when you've observed the bug on #304. You can please also provide the timezones of your device and the Calendar App.**

As I explain above, in my point of view, the plugin worked well till the version 4.5.0. Maybe if you provide more details we'll be able to reproduce it.

**Comment by Freundschaft** [comment]
the version where I encountered the error was 4.5.0, I already posted the code I used to reproduce the error. The OS was android 6.
The timezone i am in is CEST UTC +2

Does this really need reproduction? from the information I posted I think the problem is quite evident.

@elbidone can you post a sample where it is working for you with createEventInteractively?

**Comment by elbidone** [comment]
No the problem is not quite evident, and it's why your previous PR raised a regression. 
As you can see the bug is not observed on previous versions of Android. It should at least alert you.
My doubts are:
- why this exception is not raised on Android 4.1 and 5.1 ?
- why on iOS there's no need to manipulate times and it works fine ?

The bug you've observed could concerns the Calendar App on Android 6, and not this plugin. Maybe you are introducing a workaround that will causes others regressions. 
I insist "all day" events work well on Android < 6.0. I didn't test on version 6.0, but if it works on previous versions your PR will break it.

**Comment by Freundschaft** [comment]
I am alerted, I'm also looking into it right now, I do believe that some problem exists, I'm thankful for the feedback and will try to collect logs to supply here about the problem I encountered.
For the time being I can also suggest that the original PR from my side can be reverted, as the first PR was introducing a regression I can confirm.

**Comment by EddyVerbruggen** [comment]
#305 has been merged and works fine for me when creating all day and regular events. Great work @Freundschaft!

**Comment by Freundschaft** [comment]
I figured out something else really weird.
according to the API, if I want to create an all day event for the 4th of may I should set the starttime to 4th of May midnight and the endtime to 5th of may midnight, that way the event covers 24 hours on the 24th of may.

On the Sony it works fine without any issues, but on the samsung using this implementation, I will see this during event creation:

screenshot_20160812-105743

but later in the calendar it will be displayed with the correct date

screenshot_20160812-110617

I will just assume that this is a bug in the calendar implementation

**Pull request merged**
